services:
  server-service:
    build:
      context: .
      dockerfile: ./Services/Server/Dockerfile
    
    hostname: server-host

    container_name: server

    ports:
      - 5000:8080

    networks:
      - backend-net

  worker:
    build:
      context: .
      dockerfile: ./Services/Worker/Dockerfile
    
    hostname: worker-host

    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge