services:

  server-service:
    build:
      context: .
      dockerfile: ./Services/Server/Dockerfile
    
    hostname: server-host

    container_name: server

    ports:
      - 5000:8080

    networks:
      - backend-net

  worker-1:
    build:
      context: .
      dockerfile: ./Services/Worker/Dockerfile
    
    container_name: worker1
    hostname: worker1-host

    networks:
      - backend-net

    environment:
      - WorkerOptions__Name=worker_1

  worker-2:
    build:
      context: .
      dockerfile: ./Services/Worker/Dockerfile
    
    container_name: worker2
    hostname: worker2-host

    networks:
      - backend-net

    environment:
      - WorkerOptions__Name=worker_2

networks:
  backend-net:
    driver: bridge