services:
  server-service:
    build:
      context: .
      dockerfile: ./Services/Server/Dockerfile

    container_name: server

    ports:
      - 5000:8080

    networks:
      - backend-net

  coordinator-service:
    build:
      context: .
      dockerfile: ./Services/coordinator/Dockerfile
    
    ports:
      - 50051:50051

    networks:
      - backend-net

  worker:
    build:
      context: .
      dockerfile: ./Services/worker/Dockerfile
    
    ports:
      - 10000:10000

    networks:
      - backend-net


networks:
  backend-net:
    driver: bridge